{{- if and .Values.rbac.create .Values.rbac.clusterRoleBinding.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "newrelic.common.naming.fullname" . }}-{{ .Release.Namespace }}
  labels:
    {{- include "newrelic.common.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "newrelic.common.naming.fullname" . }}-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "newrelic.common.serviceAccount.name" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
