name: persistancy
port: 8080

hpa:
  minReplicas: 2
  maxReplicas: 4

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
