apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-license
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
type: Opaque
data:
  license: {{ $licenseKey | b64enc }}
